### PR TITLE
Update to 1.6, fix some bugs - disable Factions, which seems to have changed their API. somebody else figure that out.

### PR DESCRIPTION
**Pull request by mcmonkey4eva**
Update to 1.6, fix some bugs - disable Factions, which seems to have changed their API. somebody else figure that out ++ fix Denizen now

### CODE REVIEW

**Comment by XxCoolGamesxX** [comment]
Cool. Can you send me the .jar so I can test on my server. Thank.

**Comment by mcmonkey4eva** [comment]
@XxCoolGamesxX - https://dl.dropboxusercontent.com/u/54130586/Sentry.jar Though I warn you, it's extremely buggy. I talked to jrbubba on an IRC... we think the bugs are likely due to it being such an early craftbukkit version. He also says he'll check it out and see what's working and fix what isn't tomorrow.

**Comment by XxCoolGamesxX** [comment]
Ok. Thank for info.

**Comment by mcmonkey4eva** [comment]
Good news ( @XxCoolGamesxX @jrbudda ) - it's mostly all working. The only problem remaining is that Human NPCs don't work (skeley/zombie/any other NPC type) are all fine -- FullWall has confirmed that this is entirely the fault of Citizens itself and Sentry will be automatically fixed when he releases the fix for Citizens, without need for new commits. (File is updated at https://dl.dropboxusercontent.com/u/54130586/Sentry.jar )

Edit: He got it all fixed... this pull-request fully 100% workingly ports sentry to 1.6 :D

**Comment by XxCoolGamesxX** [comment]
Yup but one of my npc are bug here photo of npc:
https://dl.dropboxusercontent.com/u/16158672/2013-07-03_14.44.28.png</img> 

Use your .jar and update to Citizens 2 - 869.

But can be bug of Citizens 2.

**Comment by mcmonkey4eva** [comment]
@XxCoolGamesxX - that is ... the weirdest... how even... what the... I've no idea what that is or how it happened, but it isn't Sentry's fault. It'd likely be a minecraft clientside error (I don't think the server ever has permission or reason to tell a client 'Now render this guy upside-down!')

EDIT: Actually, it's a joke Dinnerbone coded into minecraft, not a bug. Dinnerbone's player model is flipped.

**Comment by XxCoolGamesxX** [comment]
Oh lol : P

**Comment by mcmonkey4eva** [comment]
Sentry 1.4.0 is still buggy, use this-
Sentry compatible with Denizen 0.9: https://dl.dropboxusercontent.com/u/54130586/Sentry.jar
Sentry compatible with Denizen 0.8: https://dl.dropboxusercontent.com/u/54130586/SentryForD08.jar

(Also, I updated both version at time of this comment, to fix a new bug - see commit details at https://github.com/mcmonkey4eva/Sentry )

Ima talk to jrbubba about fixing his version, since he refuses to use my pull req.

@XxCoolGamesxX @jrbudda 

(Not sure who's following this, linking you both as you might both be interested)

**Pull request closed without merging**
